name: 'log'
run-name: 'logrun'
on:
  workflow_dispatch:
    inputs:
      incomingRequest:
        description: "request payload"
jobs:
  logjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v7
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // writes the incomingRequest payload
            // content to a new file in the repo named
            // using uuid, then commits the repo and
            // pushes the commit
            const fs = require('fs');
            const path = `./.logs/${crypto.randomUUID()}.json`;
            // write the payload to the file
            const githubContext = JSON.parse(process.env.GITHUB_CONTEXT);
            const incomingRequest = githubContext.event.inputs.incomingRequest;
            fs.writeFileSync(path, incomingRequest);
      - name: Set up mutex
        uses: ben-z/gh-action-mutex@v1.0-alpha-7
      - run: |
          echo "I am protected!"
          git pull
          git add .
          git commit -m "add log"

      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: "[add log]"
      #     commit_user_name: Bot McBotface
      #     commit_user_email: lepetitg+bot@gmail.com
      #     commit_author: Bot Botetsky <lepetitg+bot@gmail.com>
